- {name: viewUser, description: "View users." }
- {name: addUser, description: "Create new user." }
- {name: editUser, description: "Edit, block or unblock user." }
- {name: deleteUser, description: "Delete user temporarily or permanently." }
- {name: resetPassword, description: "Reset password of other users." }
- {name: viewUserGroup, description: "View user groups." }
- {name: manageUserGroup, description: "Manges user groups (add/edit/delete)." }
- {name: moderatePermission, description: "Manges group permissions." }