- {name: viewPrayer, description: "View prayer requests." }
- {name: addPrayer, description: "Create new prayer request." }
- {name: editPrayer, description: "Edit prayer request." }
- {name: deletePrayer, description: "Delete prayer request." }